language: haskell
ghc: 7.8.3

before_install:
  - openssl aes-256-cbc -K $encrypted_68787bd95177_key -iv $encrypted_68787bd95177_iv -in travis_rsa.enc -out travis_rsa -d
  - mkdir -p ~/.ssh/id_rsa
  - cp travis_rsa ~/.ssh/id_rsa

install: scripts/install.sh
script: scripts/build.sh
after_success: scripts/deploy.sh
after_script: scripts/clean.sh
