language: haskell
ghc: '8.0'
sudo: false
install: scripts/install.sh
script: scripts/build.sh
before_deploy:
  - openssl aes-256-cbc -K $encrypted_1fe6220ef9db_key -iv $encrypted_1fe6220ef9db_iv -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
