language: haskell
ghc: 7.8.3

install: scripts/install.sh
script: scripts/build.sh
after_success:
  - echo "* Decrypting SSH key..."
  - openssl aes-256-cbc -K $encrypted_68787bd95177_key -iv $encrypted_68787bd95177_iv -in travis_rsa.enc -out travis_rsa -d
  - chmod 700 travis_rsa
  - cp travis_rsa ~/.ssh/id_rsa
  - scripts/deploy.sh
after_script: scripts/clean.sh
