version: 2
defaults:
  working_directory: /tmp

jobs:
  build:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.yaml" }}-{{ checksum "scripts/install.sh" }}
      - run: scripts/install.sh
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.yaml" }}-{{ checksum "scripts/install.sh" }}
      - run: scripts/build.sh
      - persist_to_workspace:
          root: /tmp
  deploy:
    docker:
      - image: ubuntu:trusty
    steps:
      - attach_workspace:
          at: /tmp
      - run: scripts/deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

