version: 2
defaults:
  working_directory: ~

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: scripts/install.sh
      - restore_cache:
          key: deps1-{{ checksum "package.yaml" }}
      - run: stack setup && stack install || exit 1
      - save_cache:
          key: deps1-{{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
      - run: scripts/build.sh
      - persist_to_workspace:
          root: ~
  deploy:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - attach_workspace:
          at: ~
      - run: scripts/deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

